resolver: lts-20.18

packages:
  - 'external-stg-syntax'
  - 'external-stg'
  - 'external-stg-interpreter'
#  - 'lambda'
#  - 'external-stg-compiler'

extra-deps:
  - souffle-haskell-3.4.0
  - type-errors-pretty-0.0.1.2@sha256:9042b64d1ac2f69aa55690576504a2397ebea8a6a55332242c88f54027c7eb57,2781

allow-newer: true
